### ISSUE TITLE
Nice logo needed for docs

### ISSUE THREAD

**Issue by AnonymousDapper** [AnonymousDapper/aiotnb#1]
Title says enough, the plain TNB logo doesn't fit quite right on the page. We need the python snake wrapped around it or something like that.

**Comment by AnonymousDapper** [comment]
Got somebody for this, expect results in a few days.

**Comment by denistsoi** [comment]
[aiotnb-deliverables.zip](https://github.com/AnonymousDapper/aiotnb/files/6768761/aiotnb-deliverables.zip)

**Comment by denistsoi** [comment]
![Favicon](https://user-images.githubusercontent.com/3061779/124573615-4cc19c80-de7c-11eb-9705-951287866a15.png)
![Cover-Spacing](https://user-images.githubusercontent.com/3061779/124573629-50552380-de7c-11eb-8278-170175ddf60b.png)
![Transparent](https://user-images.githubusercontent.com/3061779/124573715-62cf5d00-de7c-11eb-83f9-1fbe8157d900.png)
![Highlight-Red](https://user-images.githubusercontent.com/3061779/124573718-6367f380-de7c-11eb-9fd0-92460e86db13.png)
![White](https://user-images.githubusercontent.com/3061779/124573727-64008a00-de7c-11eb-851c-0363898cd14c.png)

**Comment by Aareon** [comment]
I love it

**Comment by AnonymousDapper** [comment]
Great!

@denistsoi Just open a new issue with the invoice/billing details when you have that written up, please.
